# Generated by Django 5.1.6 on 2025-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
