# Generated by Django 5.1.6 on 2025-05-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_cart_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('entregada', 'Entregada')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
