# Generated by Django 5.2 on 2025-05-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('recibido', 'Recibido')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
    ]
